### ISSUE TITLE
Services must specify compute resources

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-creator-backend#101]
Otherwise it could hit the quota limit in Pro clusters real soon: https://docs.okd.io/latest/dev_guide/compute_resources.html#dev-compute-resources

**Comment by quintesse** [comment]
I created the [utility functions](https://github.com/fabric8-launcher/launcher-creator-backend/commit/99536ed95a871b5cf74ba60be5dd1e35cc961ed2) for setting the limits, can you figure out what the actual values should be @gastaldi ?

**Comment by gastaldi** [comment]
@quintesse I have created https://issues.jboss.org/browse/RHOAR-29 in March, 2018, asking for the runtime owners to add this to their templates, but at the time of this comment, that is still open. 

Although I feel a bit reluctant in adding any value in there that may impact our MVP, I'll add some values that I think it would make sense given the generated code and based on the actual consumed memory/CPU by the service in the OpenShift Console, meaning that they must be reviewed by the runtime owners.

**Comment by quintesse** [comment]
Seems like a good idea @gastaldi !
