### ISSUE TITLE
Replace "greetingEndpoint" and "dbEndpoint" source mappings with actual file names

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-creator-backend#105]
![screenshot from 2018-12-06 14-54-10](https://user-images.githubusercontent.com/54133/49598933-dcbaa500-f966-11e8-8394-d38eabd9dedd.png)

**Comment by quintesse** [comment]
This is already implemented in the backend, so perhaps it's the frontend that isn't showing them yet?

**Comment by quintesse** [comment]
Welcome App issue, see https://github.com/fabric8-launcher/launcher-creator-welcome-app/issues/72 . Closing
