### ISSUE TITLE
NodeJS has no `/health` endpoint

### ISSUE THREAD

**Issue by quintesse** [fabric8-launcher/launcher-creator-backend#110]
The NodeJS platform doesn't have a default `/health` endpoint. It should.

(It should just return 200, preferably with the word "OK")

**Comment by quintesse** [comment]
Can you take a look at this @edewit ? Thanks!

**Comment by gastaldi** [comment]
The Health endpoint is already there, but is ` /api/health/liveness`  and `/api/health/readiness`  (see https://developers.redhat.com/blog/2018/06/11/container-native-nodejs-istio-rhoar/).
Closing
