### ISSUE TITLE
Pass image url to WA

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-creator-backend#111]
Trying to solve this WA issue https://github.com/fabric8-launcher/launcher-creator-welcome-app/issues/50

The solution is to figure out what those links are and have the Backend pass that info to the WA

You'd have to add an extra line `shared.runtimeImageUrl` to each of the platform generators, just after this line: https://github.com/fabric8-launcher/launcher-creator-backend/blob/master/catalog/generators/platform-thorntail/index.ts#L19

**Comment by quintesse** [comment]
Out-of-date. Closing.
