### ISSUE TITLE
Git rid of "framework" in favor of using "runtime" everywhere

### ISSUE THREAD

**Issue by quintesse** [fabric8-launcher/launcher-creator-backend#114]
Right now we use `framework` for frontend technologies and `runtime` for backend ones. But this distinction is unnecessary and even harmful. We have to get rid of it and use only the concept of "runtimes".

**Post-MVP**

**Comment by quintesse** [comment]
@edewit for the frontend it would simply boil down to two things:

 - everywhere you use the word "framework" you now use "runtime"
 - there's no `framework.name` enum anymore, only `runtime.name`, but the items have a `metadata.categories` where you can see if it is meant for the frontend or the backend

@ia3andy for the WA it's only:

 - everywhere you use the word "framework" you now use "runtime"

**Comment by ia3andy** [comment]
@quintesse https://github.com/fabric8-launcher/launcher-creator-welcome-app/pull/81

**Comment by quintesse** [comment]
Thanks guys, everything merged!
