### ISSUE TITLE
Thorntail+MySql/PSQL: PUT doesn't work for database capability

### ISSUE THREAD

**Issue by quintesse** [fabric8-launcher/launcher-creator-backend#117]
See https://github.com/fabric8-launcher/launcher-planning/issues/189

There's an error in the logs about duplicate keys.

**Comment by gastaldi** [comment]
According to fabric8-launcher/launcher-planning#189, this is not a bug. The fruit name is marked to be unique and you get a constraint violation error if you attempt to insert a fruit with the same name.
