### ISSUE TITLE
`OUTPUT_DIR` for react is wrong

### ISSUE THREAD

**Issue by edewit** [fabric8-launcher/launcher-creator-backend#144]
on the build configuration for react `OUTPUT_DIR` is set to `./dist/<project-name>/`, but for react it should be `build`

**Comment by quintesse** [comment]
Thanks @edewit 
I think what we need as well is proper tests for the web-apps in the Creator :-)
Right now they are not tested at all.

**Comment by edewit** [comment]
Seems to me that you now broken angular and fixed react?

**Comment by quintesse** [comment]
@edewit you're still looking at the old commit, @gastaldi did indeed first "fix" Angular by mistake, but then corrected it :-)

**Comment by edewit** [comment]
Okay, then he didn't put the right reference in this issue.
