### ISSUE TITLE
Root folder in ZIP should have proper name

### ISSUE THREAD

**Issue by quintesse** [fabric8-launcher/launcher-creator-backend#15]
Right now it's hard-coded to `app`. We should make it use the name of the application.

**Comment by quintesse** [comment]
This is actually only when creating the zip using the command line script. So this really is not important. Closing.

**Comment by ALRubinger** [comment]
I agreed with your first assessment, @quintesse. :)

**Comment by quintesse** [comment]
:-)

The command line script will probably only ever used in development by someone testing the project generation. So I'm not so sure it's necessary. But we can always reopen if anyone ever complains.

**Comment by quintesse** [comment]
This was already done at some point.
