### ISSUE TITLE
Add PORT=8080 to imported apps

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-creator-backend#159]
Some apps (specifically the ones using Node.js Express) run on a different port than 8080 (used in the Routers and Health Check). 

This can be overridden by specifying the `PORT=8080` environment variable in the DeploymentConfig

**Comment by gastaldi** [comment]
Example: https://github.com/heroku/node-js-sample/blob/master/index.js#L4

**Comment by quintesse** [comment]
Ok, so we'd need to detect that we're dealing with Node.js and perhaps even Express.

**Comment by gastaldi** [comment]
Maybe by the builder image for now?

**Comment by ALRubinger** [comment]
Or maybe we try to be even dumber and just let the user specify sysprops, suggesting we add PORT=8080?  I'm not sure if this is widespread enough in its usage that as a convention we apply it as a default.  But we may like to recommend to users they think about what port their app is listening on and recommend they apply some setting to expose it?

Also this is just the sysprops side where the app defines what port it binds to; there's also the element of exposing that port in the container.  So everything has to be all matchy-matchy and we gotta give the user avenues to do that without being too smart/opinionated about it.

**Comment by quintesse** [comment]
Btw I just checked and S2I images indeed all seem to only expose port 8080. So that means that setting ENV vars is the only viable work-around.

**Comment by gastaldi** [comment]
Looks like this is not a crappy solution after all :laughing:

**Comment by ALRubinger** [comment]
> Looks like this is not a crappy solution after all

Oh yes it is. :)  It's just that with opinionated base images we have to be opinionated in the same way.  I'd prefer we, looking forward, explore how to give the user greater control over the ports they bind to in the application code.

But this is a fine first cut given the constraints of the systems we're in!

**Comment by quintesse** [comment]
>  I'd prefer we, looking forward, explore how to give the user greater control over the ports they bind to in the application code.

I think that's hard, in fact right now I don't see how to do it except by providing base images for everything ourselves.

First I thought that perhaps switching to chained builds could solve this but most public Docker images (for example for NGINX) use a fixed port 8080 too, so'd we'd have to come up with alternatives for those too. Not really a viable solution IMO.

I'm guessing clear documentation in setting proper expectations is the way to go: "the imported code will need to use port 8080 to communicate by default or needs to ability to set the port to 8080 via environment variables"

**Comment by ALRubinger** [comment]
Agreed, @quintesse!  I meant "we", Red Hat. :)

**Comment by gastaldi** [comment]
Works as advertised. Closing
