### ISSUE TITLE
Error while building DotNet project

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-creator-backend#162]
```
Cloning "https://github.com/gastaldi/spotted-cows.git " ...
	Commit:	91b59d970cc106214e1f9995ba1e55632a6500d7 (Initial commit)
	Author:	Red Hat Developers Launcher <45641108+redhat-developers-launcher@users.noreply.github.com>
	Date:	Tue Mar 19 23:03:53 2019 +0000
Microsoft (R) Build Engine version 15.9.20.63311 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

Program.cs(5,10): error CS1001: Identifier expected [/opt/app-root/src/spotted-cows.csproj]
Startup.cs(13,7): error CS1001: Identifier expected [/opt/app-root/src/spotted-cows.csproj]
Startup.cs(15,10): error CS1001: Identifier expected [/opt/app-root/src/spotted-cows.csproj]
```

@omajid can you have a look?

**Comment by gastaldi** [comment]
Hm, it looks like `{{.dotnet.namespace}}` was not evaluated properly in Program.cs. @quintesse thoughts?

**Comment by gastaldi** [comment]
Ahh, it could be the https://github.com/fabric8-launcher/launcher-creator-backend/blob/92cc69a67a505ca46caca102c73a3739ae191645/catalog/capabilities/database/info.json#L57-L88 that you said it was missing?

**Comment by quintesse** [comment]
Possibly, but given that your issue doesn't tell me how to reproduce that error I can't really be sure 100% hehe

But yeah, 99.9% sure it's that. It should already be fixed.

**Comment by gastaldi** [comment]
Fixed in https://github.com/fabric8-launcher/launcher-creator-backend/commit/f7b634fe363539f0ee0ac464b67ce830b09b2158, closing

**Comment by gastaldi** [comment]
Oops, my mistake, it still happens

**Comment by gastaldi** [comment]
@quintesse to reproduce just deploy a .NET backend using the frontend UI

**Comment by omajid** [comment]
Sorry about this. None of the steps in the README or the unit tests exercised this :( Is there a way I can (or could have) seen the failures locally?

**Comment by gastaldi** [comment]
@omajid I think in order to reproduce that you'd need to:
-  run launcher (`launcher-frontend`, `launcher-backend` and `launcher-creator-backend`) locally or;
- ` yarn start:dev` and curl the `/zip` endpoint with the appropriate parameters (see what's sent in the Chrome Console window) to fetch the generated ZIP

**Comment by quintesse** [comment]
> Sorry about this. None of the steps in the README or the unit tests exercised this :(

@omajid it happened after rebasing against master. All the changes you made were correct you just hadn't done them for the new additions that had been made in master since you started to develop your .net support. Don't worry, it's all fixed now.
