### ISSUE TITLE
.NET needs support for Health Checks

### ISSUE THREAD

**Issue by quintesse** [fabric8-launcher/launcher-creator-backend#164]
Health Checks are not implemented right now:

```
            // TODO This needs to be implemneted in a higher-level generator
            // setDefaultHealthChecks(res);
```

**Comment by quintesse** [comment]
@omajid could you check this is correct? Thanks!

**Comment by omajid** [comment]
Just for the historical record, this was improved via https://github.com/fabric8-launcher/launcher-creator-backend/pull/166
