### ISSUE TITLE
Update Quarkus logo

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-creator-backend#175]
RHT only, sorry: https://drive.google.com/file/d/1FCdtaAGyhPmT5co_xH0kXVMoOP-lsaMz/view

This is a temp one while rebranding is being done, but at least it'll give a white BG

**Comment by gastaldi** [comment]
Quarkus has a new and definitive logo: 

![image](https://user-images.githubusercontent.com/54133/57309981-665dd280-70bf-11e9-900a-f6c046998a3c.png)

SVG in http://design.jboss.org/quarkus/
