### ISSUE TITLE
Support runtime filtering

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-creator-backend#179]
It should be possible to filter out for example Quarkus and .Net from the possible runtimes

**Comment by gastaldi** [comment]
Requested by @tqvarnst

**Comment by edewit** [comment]
Should this be dynamic e.g. based on the url one uses or do we use a environment var to start the backend? Because I thought we already had the last option right @gastaldi ?

**Comment by gastaldi** [comment]
@edewit It should be fixed in an environment variable. We only have this feature for the `Create from example` flow at the moment

**Comment by quintesse** [comment]
@gastaldi to me this seems a frontend issue and then we could even add the additional feature of having a dynamic option as well because the runtime teams definitely want that (they are not going to maintain their own Launcher applications just to be able to filter out runtimes)

**Comment by quintesse** [comment]
_If_ we are sure we want to make this a backend feature anyway then I'd make it an ENV var that the Launcher Backend also supports so we can filter out runtimes in the example flow too (but that's actually why it seems to me it's a better place to do it in the frontend)

**Comment by gastaldi** [comment]
@quintesse I wouldn't say we are sure but for that to happen I'd expect an unification of both approaches (booster-catalog vs launcher-creator-backend JSONs).

**Comment by quintesse** [comment]
Added a new issue in the frontend. Closing this one .

**Comment by gastaldi** [comment]
Reopening, as per @tqvarnst's thread:

>I like the idea of being able to limit on URL parameter/path, but that use-case is a bit different. What I'm describing is more of a use-case where an enterprise installs a local OpenShift cluster and wants to use the Launcher to provide a great development experience for their developers. However, they do not want to include certain runtimes like Quarkus since it is not considered stable enough at this point. A bonus would also be if you could actually filter away community version of runtimes and only show the "STABLE" or as they are called now RHOAR versions.

**Comment by quintesse** [comment]
@gastaldi I still don't see why that can't be done in the frontend. The frontend has to implement filtering anyway. So why on earth are you guys so determined to implement it ion the backend?
Each time we've done frontend stuff in the backend (wizards, forms, filtering) we've ended up moving it to the frontend in the end.

**Comment by gastaldi** [comment]
>Each time we've done frontend stuff in the backend (wizards, forms,
filtering) we've ended up moving it to the frontend in the end.

Well, the launcher-backend has the catalog filter feature implemented for
ages
https://github.com/fabric8-launcher/launcher-backend/blob/master/README.md#filtering-the-booster-catalog
and that doesn't seem to have been moved to the frontend :)

I may be definitely missing something here, but if the filtering is done in
the frontend how do you configure that?

**Comment by quintesse** [comment]
> and that doesn't seem to have been moved to the frontend :)

Wdym? The frontend isn't using that to filter, it's using it's own filtering. It was used by the old UI but that was a long time ago.

> how do you configure that to resolve the requirement proposed by Thomas?

We have ENV vars in the frontend too, right? https://github.com/fabric8-launcher/launcher-frontend/blob/master/openshift/template.yaml#L87-L132 But I'm guessing any other way to configure the frontend would do.

Then you'd just have a simple function somewhere (pseudocode):

```
function runtimeFilter() {
   return ENV.get("RUNTIME_FILTER") || request.params("runtimes")
}
```

Meaning the filtering could either be fixed at startup time using an ENV var (or whatever) or dynamically at runtime by using something from the URL/request.

(Now, I'm sure in real life this will be more complex, but still, the idea seems simple enough)

**Comment by gastaldi** [comment]
>Wdym? The frontend isn't using that to filter, it's using it's own filtering. It was used by the old UI but that was a long time ago.

My point is that the launcher-backend is already capable of filtering based on an expression. The frontend and the VSCode plugin can consume boosters and do not care about filtering (the integr8tly team uses this feature to restrict the available options)

IMHO it's much better (and easier) to read ENV vars from a backend service and return the filtered data rather than do it in the frontend, which will require a service that reads the ENV vars, writes it to a JSON and makes it available to the frontend (just to reuse that value again when requesting data to the backend). 

In another words, It's all fun and games until a new frontend or integration is introduced :)

**Comment by quintesse** [comment]
> The frontend and the VSCode plugin can consume boosters and do not care about filtering (the integr8tly team uses this feature to restrict the available options)

I'm pretty sure the VSCode pluigin would be much better off to do its own filtering than leaving it to the backend to improve response time in the UI, just like our own UI.

So it's only useful for those that a) want a static filter and b) are willing to run their own Launcher.

It does not solve the situation for the runtime teams that _also_ want to filter but do _not_ each want to run their own Launcher.

So again I ask: why solve this only for a single use-case (which is basically the integreatly team) while we could solve several other important use-cases at the same time by implementing it in the frontend? :-)

**Comment by quintesse** [comment]
> which will require a service that reads the ENV vars, writes it to a JSON and makes it available to the frontend

Is it really that complex? I thought it would just be a change in the startup script? https://github.com/fabric8-launcher/launcher-frontend/blob/master/scripts/entrypoint.sh

**Comment by gastaldi** [comment]
>I'm pretty sure the VSCode pluigin would be much better off to do its own filtering than leaving it to the backend to improve response time in the UI, just like our own UI.

Lol, that statement makes no sense to me, I'd assume the less work in the plug-in the better :wink:

>So it's only useful for those that a) want a static filter and b) are willing to run their own Launcher.

YES! That is the use case that Thomas described. Exposing data beyond the boundaries of what this filter defines should be prohibited.

**Comment by quintesse** [comment]
> Lol, that statement makes no sense to me, I'd assume the less work in the plug-in the better 

Wdym? The plugin supports all runtimes, why would it even do _any_ filtering?

> YES!

Yes indeed, and then you stopped reading, because I said:  "It does not solve the situation for the runtime teams that also want to filter but do not each want to run their own Launcher."

**Comment by gastaldi** [comment]
I give up. Closing this issue

**Comment by quintesse** [comment]
There's now a `CREATOR_RUNTIME_FILTER` ENV var. It can contain a comma-separated list of allowed runtime IDs or if it starts with `!` a list of disallowed runtime IDs. The `/enums` endpoint will then return a specific copy of the enumerations where the `runtime.name` elements (and only those) will have been filtered according to the filter.

Looks like a subpar solution to me but it seems to be what everyone wants.
