### ISSUE TITLE
Make sure that Vert.x REST + Database works

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-creator-backend#31]
- [x] *MY_DATABASE_SERVICE_HOST* environment variable is not set when deployed, it tries to reach `localhost`
- [x] *DB_USERNAME* and *DB_PASSWORD* environment variables are not set when deployed
- [x] Make sure file structure of the generators is properly separated (platform should _only_ contain common files)
- [x] Make sure project is a simple as possible
- [x] Make sure the project supports health checks

**Comment by quintesse** [comment]
Yeah, that's part of the TODO that's here: https://github.com/fabric8-launcher/launcher-creator-backend/blob/master/catalog/generators/database-crud-vertx/index.ts#L22

The copying of files and patching them is already done but we need to call `setDeploymentEnv()` (from `resources7index.ts`) to set the proper ENV vars (and make them point to the Secret that was generated for the database)

**Comment by quintesse** [comment]
So what we still have to figure out is how to merge the two code bases in such a way that both keep working. I think there's basically only a single problem: the entry point to the application. The base Vert.x platform Generator and the REST one both use `HttpApplication` while the Database one uses `CrudApplication`. Both set up a HTTP server and I'm guessing that's not possible, so we'd need to set up the code in some way that all Capabilities can easily add their own part to a single file, right?

**Comment by quintesse** [comment]
NB: this is actually a dup of #10 but I'll close that one instead.

**Comment by quintesse** [comment]
@gastaldi I think this _should_ work now. See what is generated now:

https://github.com/quintesse/generated-app-ex/blob/master/.openshiftio/application.yaml#L109-L139

**Comment by quintesse** [comment]
Cool. I'll move the "Make sure project is a simple as possible" to a new issue though.
