### ISSUE TITLE
Create an insertAfter filter

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-creator-backend#58]
For cases where code snippets need to be inserted after a marker comment:

 ```
private RouterConsumer[] getRouterConsumers() {
    return new RouterConsumer[]{
      // TODO: Add new RouteConsumers here
    }
}
```

**Comment by quintesse** [comment]
Done, see: https://github.com/fabric8-launcher/launcher-creator-backend/blob/master/lib/core/template/transformers/insert.ts

**Comment by quintesse** [comment]
See tests for examples: https://github.com/fabric8-launcher/launcher-creator-backend/blob/master/test/template/transformer.insert.test.ts
