### ISSUE TITLE
Make sure that the Vert.x (and REST + Database) Generators are as simple as possible

### ISSUE THREAD

**Issue by quintesse** [fabric8-launcher/launcher-creator-backend#61]
Right now there are still unnecessary files and code about. We should make the project as simple as possible to properly work as an example for people on how to do things (without using RH-specific libraries etc):

- [ ] Remove `booster-parent` from the POM file
- [ ] Remove any references to `booster` in any files (change to `creator` if necessary)

Any others to add?

**Comment by gastaldi** [comment]
@cescoffier perhaps this may be something you can work on?

**Comment by cescoffier** [comment]
@gastaldi I can only take the decision for the Vert.x boosters. 

As I said, I'm all for removing the booster parent - however, it's not going to be done in the very near future. Mid-December seems more reasonable. 

About the name change, what does it mean? Does it impact all boosters? Should we keep a version with "booster" another one with "creator"?

**Comment by quintesse** [comment]
> About the name change, what does it mean?

That one wasn't really meant for you @cescoffier , just ignore it :-)

**Comment by quintesse** [comment]
out-of-date. Closing.
