### ISSUE TITLE
Investigate putting Generators in remote repos

### ISSUE THREAD

**Issue by quintesse** [fabric8-launcher/launcher-creator-backend#70]
We'd need to figure out if doing that would make the Runtime team's life easier without making ours more difficult. And if so what solution to use?

 - git submodules
 - npm modules
 - ???

Also:

 - Put the entire Generator in there (including code)?
 - Just the files

The first option would mean we'd need access to all those repos or we'd be very restricted in the kind of changes we could make to the core.

**Comment by gastaldi** [comment]
Although git submodules may be tempting, I'd prefer npm modules, since it has the advantage of having @dependabot to automatically update `launcher-creator-backend` once a new release is available (no work required from us)

**Comment by quintesse** [comment]
@gastaldi only if they were published as public modules, but we already decided that we couldn't do that because there might be code we are not allowed to put there. Unless @dependabot is able to use private repositories?

**Comment by quintesse** [comment]
To me it also means that you lose out on the staging vs production workflow. You either publish a new version or you don't. So if you publish you automatically push the module through staging and production. there's no way you can say: publish this module for testing on staging only, I don't want it yet in production.

Also, right now we could also have the advantage of not having to do anything: just give them push access to the repo ;-)

**Comment by gastaldi** [comment]
> but we already decided that we couldn't do that because there might be code we are not allowed to put there

I don't think that still holds true. We are an open source company and the generated code should be available for everyone.

>there's no way you can say: publish this module for testing on staging only, I don't want it yet in production.

Maybe I wasn't totally clear when I said that it won't require work from us: Promotion to production doesn't happen automatically, this will still require us to change the YAML deployment in saas-launchpad (like we do with launcher-backend and launcher-frontend)

**Comment by quintesse** [comment]
> I don't think that still holds true. We are an open source company and the generated code should be available for everyone.

I don't think that's true either. We obviously have code that's only available with support subscriptions. All our RHOAR images are like that for example. So even _using_ a RHOAR image in our templates might be a problem. (People create an app based on RHOAR images and push the result to Docker Hub and then get a message from RH Legal telling them not to do that)

> like we do with launcher-backend and launcher-frontend

For the Launcher we've created an entire system for people to decide which boosters are in staging and which are in development. We'd have to make something similar, perhaps by making people update version numbers in the core backend code. Which is entirely possible but makes the splitting into separate modules less easy than just directly updating it in the code and creating a PR.

**Comment by quintesse** [comment]
Out-of-date. Things have changed a lot. Discussion will need to be restarted on this if necessary, Closing.
