### ISSUE TITLE
Add new info for the welcome app.

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-creator-backend#76]
In order to have as much info as possible in the Welcome App as shown there:
https://fabric8-launcher.github.io/launcher-creator-welcome-app/

The backend need to add new info in the template for the Welcome App.

It is better to have them in the json config when possible.

Shared infos:
- [x] repository url
- [x] console url (will be template parameter ´OPENSHIFT_CONSOLE_URL´)
- [x] runtime info (name/language + icon + version + desc)
- [x] runtime image name
- [x] name of runtime service (already there)

Database infos:
- [x] db type name, desc and icon
- [x] database image name
- [x] name of database service

Database credentials are hard coded for now: `dbuser:secret`

**Comment by ia3andy** [comment]
Naming of those attributes is not defined and can be adapted. It is better to have them in the json config when possible.

Shared infos:
- repositoryUrl
- consoleUrl
- runtime info (name/language + icon + version + desc)
- base image name

Database infos:
- db type name, desc and icon
- image name
- service name

Database credentials are hard coded for now: `dbuser:secret`

**Comment by quintesse** [comment]
@ia3andy db info doesn't have description and icon so if you want that too you need to open a different issue for that. Preferably with a PR :-D

**Comment by quintesse** [comment]
@ia3andy All information you requested should now be available (except for the fields mentioned in my previous comment :point_up: )

**Comment by quintesse** [comment]
I've also added the two that are only available as ENV vars to the Build as REACT_APP vars: `REACT_APP_OPENSHIFT_CONSOLE_URL` and `REACT_APP_SOURCE_REPOSITORY_URL`

**Comment by quintesse** [comment]
@ia3andy we can close this issue, right?

**Comment by quintesse** [comment]
No response, closing.
