### ISSUE TITLE
Generate README.adoc instead of README.md

### ISSUE THREAD

**Issue by edewit** [fabric8-launcher/launcher-creator-backend#81]
The `launcher-backend` generates a project with a `README.adoc` but creator uses markdown. To make linking to this document easier for clients it would be good to only create on format.

**Comment by edewit** [comment]
Also we could maybe improve on the contents of this file

**Comment by quintesse** [comment]
You're right of course. It's this weird things where the Boosters actually have README.md files which are then replaced with README.adoc files by the Launcher.

**Comment by quintesse** [comment]
Out-of-date. Closing.
